# Generated by Django 3.1.1 on 2020-09-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('setup_specs', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=50)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('guage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='maintenance date')),
                ('service', models.CharField(choices=[('R', 'Restring'), ('S', 'Setup'), ('E', 'Electronics'), ('C', 'Structural Repair'), ('F', 'Fretwork')], default='R', max_length=1)),
                ('technician', models.CharField(default='Me', max_length=50)),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.axe')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='axe',
            name='strings',
            field=models.ManyToManyField(blank=True, to='main_app.String'),
        ),
    ]
