# Generated by Django 3.1.1 on 2020-09-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='AxePhoto',
        ),
        migrations.CreateModel(
            name='StringPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.string')),
            ],
        ),
    ]
