# Generated by Django 3.1.1 on 2020-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='axe',
            name='strings',
            field=models.ManyToManyField(to='main_app.String'),
        ),
    ]
