# Generated by Django 3.1.1 on 2020-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200917_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='material',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
